### ISSUE TITLE
upgrade to symfony 3

### ISSUE THREAD

**Issue by Wohlrajh** [ddmaster/PostgreSearchBundle#5]
For my project i need symfony 3.3 in composer

**Comment by ddmaster** [comment]
I don't work with Postgre anymore. I cannot test bundle with sf3 and
Postgre.
You can send pull request with improvements for sf3 or create your own fork.

2017-08-24 15:55 GMT+03:00 fred <notifications@github.com>:

**Comment by Wohlrajh** [comment]
thanks for you work
