### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simara-svatopluk** [ddmaster/PostgreSearchBundle#8]
Hello @ddmaster,

I would like to fork Your library, but I would like to have Your permission first. Could You please provide a license? For example MIT would be great

.... and adding a license is super easy https://help.github.com/articles/adding-a-license-to-a-repository/ :-)

**Comment by ddmaster** [comment]
Hello

Yes, sure) Added https://github.com/ddmaster/PostgreSearchBundle/blob/master/LICENSE

**Comment by simara-svatopluk** [comment]
Wow, thanks!

That was ultrasonic fast response time :-)
